apiVersion: batch/v1
kind: Job
metadata:
  name: pi04
spec:
  template:
      spec:
        containers:
        - name: pi04
        image: perl:5.34.0
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(1000)"]
      restartPolicy: Never
    backoffLimit: 4
